name: Build and Release

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-latex-recommended texlive-xetex latexmk

      - name: Install Calibre for EPUB conversion
        run: |
          sudo apt-get install -y calibre

      - name: Build standard PDF
        run: |
          make

      - name: Build Kindle PDF
        run: |
          make kindle

      - name: Build EPUB
        run: |
          make epub

      - name: Create source archive
        run: |
          tar -czf practical-c-book-source.tar.gz --exclude='.git' --exclude='*.aux' --exclude='*.log' --exclude='*.out' --exclude='*.toc' --exclude='*.fdb_latexmk' --exclude='*.fls' --exclude='*.synctex.gz' .</parameter>

      - name: Rename output files
        run: |
          cp main.pdf practical-c-book.pdf
          cp main_kindle.pdf practical-c-book-kindle.pdf
          cp main.epub practical-c-book.epub

      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            practical-c-book.pdf
            practical-c-book-kindle.pdf
            practical-c-book.epub
            practical-c-book-source.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts for non-tag builds
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: book-artifacts-${{ steps.get_version.outputs.VERSION }}
          path: |
            practical-c-book.pdf
            practical-c-book-kindle.pdf
            practical-c-book.epub
            practical-c-book-source.tar.gz
          retention-days: 30</parameter>
